insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','company_code','账套');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','dmonth','月份');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','order_number','订单行号');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','order_detail_code','订单号');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','cinvname','名称');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','income','收入金额');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','material_cost','采购材料成本');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','manufacture_cost','制造费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','labor_cost','人工费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','cost_sum','成本小计');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','profit_sum','毛利小计');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','profit_sum_radio','毛利率小计');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','mgr_cost','管理费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','run_cost','营业费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','cost_total','合计成本');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','profit','利润');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','profit_radio','利润率');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('order_cost','invoice_id','发票号');


insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','ddate','订单日期');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','company_code','账套');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','order_detail_code','订单号');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','order_number','行号');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','customer_name','客户名称');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','order_value','订单金额');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','product_code','产品编码');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','product_name','产品名称');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','return_amount','回款金额');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','return_plan_date','应回款日期');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','return_date','回款收到日期');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','profit_rate','利润率');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','material_cost','材料成本');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','manufacture_cost','制造费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','labor_cost','人工成本');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','mgr_cost','管理费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','shipping_cost','船务费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','profit','退税前利润');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('crm_mgr','cdep_name','组别');


insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','ddate','下单日期');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','company_code','账套');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','order_detail_code','订单号');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','sale_name','业务员');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','customer_name','客户名');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','product_code','产品编码');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','product_name','产品名称');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','profit_rate','提点');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','exchange_rate','下单当月汇率');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','order_value','订单金额');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','retained_profit','净利润');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','current_amount','本月到账金额');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','profit_amount','提成金额');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','out_amount_rate','提成占净利比');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('sale_kpi','out_total_rate','占提成总额比例');


insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','ddate','日期');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','csocode','订单号');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','irowno','订单行号');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','company_code','账套');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','cinvcode','存货编码');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','cinvname','存货名称');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','material_cost','采购材料成本');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','manufacture_cost','制造费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','labor_cost','人工费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','mgr_cost','管理费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','shipping_cost','船务费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','inatsum','本币金额');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','profit','利润');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','quotation_material_cost','报价材料费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','quotation_manufacture_cost','报价制造费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','quotation_labor_cost','报价人工费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','quotation_mgr_cost','报价管理费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','quotation_shipping_cost','船务费用');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','quotation_profit','报价利润');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','quotation_unitprice','报价单价');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','quotation_cost','报价成本');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','actual_cost','实际成本');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','diff','差异');
insert into `auth_column` (`table_name`, `column_filed`, `column_name`) values('quotation_total','diff_radio','差异率');








insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('1','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('2','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('3','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('4','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('5','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('6','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('7','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('8','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('9','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('10','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('11','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('12','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('13','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('14','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('15','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('16','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('17','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('18','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('19','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('20','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('21','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('22','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('23','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('24','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('25','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('26','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('27','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('28','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('29','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('30','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('31','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('32','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('33','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('34','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('35','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('36','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('37','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('38','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('39','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('40','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('41','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('42','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('43','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('44','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('45','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('46','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('47','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('48','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('49','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('50','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('51','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('52','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('53','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('54','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('55','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('56','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('57','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('58','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('59','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('60','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('61','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('62','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('63','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('64','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('65','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('66','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('67','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('68','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('69','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('70','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('71','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('72','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('73','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('74','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('75','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('76','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('77','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('78','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('79','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('80','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('81','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('82','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('83','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('84','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('85','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('86','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('87','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('88','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('89','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('90','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('91','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('92','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('93','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('94','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('95','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('96','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('97','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('98','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('99','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('100','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('101','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('102','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('103','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('104','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('105','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('106','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('107','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('108','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('109','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('110','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('111','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('112','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('113','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('114','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('115','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('116','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('117','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('118','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('119','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('120','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('121','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('122','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('123','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('124','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('125','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('126','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('127','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('128','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('129','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('130','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('131','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('132','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('133','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('134','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('135','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('136','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('137','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('138','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('139','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('140','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('141','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('142','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('143','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('144','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('145','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('146','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('147','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('148','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('149','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('150','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('151','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('152','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('153','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('154','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('155','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('156','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('157','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('158','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('159','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('160','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('161','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('162','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('163','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('164','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('165','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('166','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('167','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('168','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('169','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('170','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('171','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('172','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('173','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('174','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('175','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('176','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('177','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('178','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('179','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('180','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('181','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('182','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('183','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('184','4','超级管理员');
insert into `auth_role_column` (`column_id`, `role_id`, `role_name`) values('185','4','超级管理员');


INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(1,4,'超级管理员')
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(2,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(3,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(4,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(5,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(6,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(7,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(8,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(9,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(10,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(11,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(12,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(13,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(14,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(15,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(16,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(17,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(18,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(19,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(20,4,'超级管理员');
INSERT INTO auth_role_resource(resource_id,role_id,role_name) VALUES(21,4,'超级管理员');




