# 服务
server:
  # 服务端口
  port: 8080

spring:
  #  profiles: dev
  # 微服务名称
  application:
    name: futuremaperp
  datasource:
    dynamic:
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      p6spy: true  # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 30
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:mysql://119.23.35.193:35001/futuremap_erp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
          username: bi
          password: FZD0YLI17K
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          max-idle: 30
          max-wait: 1000
          min-idle: 5
          initial-size: 5
          min-evictable-idle-time-millis: 600000
          time-between-eviction-runs-millis: 300000
          validation-query: select 1 from dual
          test-on-borrow: true
          test-while-idle: true
          log-abandoned: true
          remove-abandoned: true
          remove-abandoned-timeout: 180

  #        erp002: #宜心 生产制造企业，出口为主，内销为辅
  #          username: mingo
  #          password: mingo789
  #          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #          url: jdbc:sqlserver://192.168.16.50:1433;DatabaseName=UFDATA_002_2016
  #        erp003: #横琴宜心 贸易出口型企业 【在珠海宜心的客户编号 EASI001】
  #          username: mingo
  #          password: mingo789
  #          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #          url: jdbc:sqlserver://192.168.16.50:1433;DatabaseName=UFDATA_003_2013
  #        erp004: #MEX 境外贸易企业  已经收尾但是里面有的订单还在执行过程中 【在珠海宜心的客户编号 W0001】
  #          username: mingo
  #          password: mingo789
  #          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #          url: jdbc:sqlserver://192.168.16.50:1433;DatabaseName=UFDATA_004_2016
  #        erp006: #澳门宜成 ESSEN 境外贸易企业【在珠海宜心的客户编号 HD154】
  #          username: mingo
  #          password: mingo789
  #          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #          url: jdbc:sqlserver://192.168.16.50:1433;DatabaseName=UFDATA_006_2019
  #        erp010: # 智拓 StoSto, 零售内销型，线上为主（包括电商系统）；【在珠海宜心的客户编号 HD151】
  #          username: mingo
  #          password: mingo789
  #          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #          url: jdbc:sqlserver://192.168.16.50:1433;DatabaseName=UFDATA_010_2011
  #          max-idle: 30
  #          max-wait: 100000
  #  redis:
  #    host: 119.23.35.193
  #    port: 6379
  #    prefix: frmtest
  #    password: fm2020
  #    lettuce:
  #      shutdown-timeout: 100 # 关闭超时时间
  #      pool:
  #        max-active: 30 # 连接池最大连接数（使用负值表示没有限制）
  #        max-idle: 10 # 连接池中的最大空闲连接
  #        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #        min-idle: 0 # 连接池中的最小空闲连接
  main:
    allow-bean-definition-overriding: true #easypoi启用覆盖
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.futuremap.*.module.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    # 逻辑删除全局字段 (默认无 设置会自动扫描实体字段)
    logic-delete-field: delStatus
    # 逻辑删除全局值（默认 1、表示已删除）
    logic-delete-value: 1
    # 逻辑未删除全局值（默认 0、表示未删除）
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

swagger:
  production: false
  basic:
    enable: true
    path: /swagger-ui.html
  user:
    username: admin
    password: admin
spring.servlet.multipart.max-file-size: 3MB
spring.servlet.multipart.max-request-size: 5MB

# 异步线程配置
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 10
      # 配置队列大小
      queue_capacity: 99999
      name:
        # 配置线程池中的线程的名称前缀
        prefix: async-service-

security:
  token:
    header: X-Auth-Token
    head: 'Bearer '  #JWT负载中拿到开头
    secret: ca$hc0w1!
    expiration: 604800 #JWT的超期限时间(60*60*24*7)

secure:
  ignored:
    urls: #安全路径白名单
      - /auth/**
      - /csrf
      - /v2/api-docs
      - /definitions/**
      - /configuration/ui
      - /swagger-resources/**
      - /configuration/security
      - /swagger-ui.html
      - /webjars/**
      - /swagger-resources/configuration/ui
      - swagger-ui.html
      - /sys/register
      - /sys/login"
      - /**