server:
  port: 3020

spring:
  application:
      name: payment-service
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: non_null
  datasource:
    #url: jdbc:mysql://bibi-pay-center.mysql.polardb.cnsh.rds.aliyuncs.com:3306/xxpaydb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    #url: jdbc:mysql://pi-uf6m31m75kac85uxz.mysql.polardb.cnsh.rds.aliyuncs.com:3306/xxpaydb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    #username: bibi_pay_center
    #password: szHLx5
    #开发
    url: jdbc:mysql://rm-wz94p9qxaqmmc2r0fo.mysql.rds.aliyuncs.com:3306/pay_center?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    #生产
    #url: jdbc:mysql://rm-wz9a15wv8z6x8v9qz4o.mysql.rds.aliyuncs.com:3306/pay_center?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: pay_center
    password: hGX2pftA6P
  # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5    # 初始化大小
    minIdle: 5        # 最小
    maxActive: 20     # 最大
    maxWait: 60000    # 获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true                    # 打开PSCache
    maxPoolPreparedStatementPerConnectionSize: 20   # 指定每个连接上PSCache的大小
    filters: stat,log4j                        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #druid:
    #    filters: stat
    #    maxActive: 20
    #    initialSize: 1
    #    maxWait: 60000
    #    minIdle: 1
    #    timeBetweenEvictionRunsMillis: 60000
    #    minEvictableIdleTimeMillis: 300000
    #    validationQuery: select 'x'
    #    testWhileIdle: true
    #    testOnBorrow: false
    #    testOnReturn: false
    #    poolPreparedStatements: true
    #    maxOpenPreparedStatements: 20
  redis:
      database: 0
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
#      password: i78kJrengi5
      pool:
          max-active: 20
  rabbitmq:
      host: ${RABBIT_MQ_HOST:192.168.1.45}
      port: ${RABBIT_MQ_PORT:5672}
      virtualHost: /
      username: admin
      password: 123456
#    支持发布确认
#      publisher-confirms: true
#    支持发布返回
#      publisher-returns: true
      listener:
          simple:
#      采用手动应答
            #acknowledge-mode: manual
            acknowledge-mode: auto
#        当前监听容器数
            concurrency: 1
#        最大数
            max-concurrency: 1
#        是否支持重试
            retry:
              enabled: true
  zipkin:
      enabled: true
  sleuth:
    sampler:
      percentage: 1

#  activemq:
#    broker-url: failover:(tcp://120.24.46.96:61616?wireFormat.maxInactivityDuration=0)
#    in-memory: true
#    pool:
#      enabled: true # 如果此处设置为true，需要加activemq-pool依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
#mybatis:
#    mapper-locations: "classpath*:mapper/*.xml"
  freemarker:
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl
      templateEncoding: UTF-8
      templateLoaderPath: classpath:/templates/

config:
  ali:
#    notify_url: http://luosheng.bibi321.com/notify/pay/aliPayNotifyRes.htm
    notify_url: https://ms.bibi321.com/api/payment/api/notify/pay/aliPayNotifyRes.htm
    return_url: https://ms.bibi321.com
  wx:
    #certRootPath: /home/pay/cert/wx
    certRootPath: D:CERT/common
    notifyUrl: https://ms.bibi321.com/api/payment/api/notify/pay/wxPayNotifyRes.htm
    refundNotifyUrl: https://ms.bibi321.com/api/payment/api/notify/pay/wxPayNotifyRes.htm

  union:
    serverContextUrl: https://ms.bibi321.com/api/paytest
    frontNotifyUrl: http://www.bibi321.com
    backNotifyUrl: https://ms.bibi321.com/api/payment/api/notify/pay/unionPayNotifyRes

logging:
  file: ./log/xxpay4spring-boot.log
  level.org.xxpay: debug

#Twitter_Snowflake 序列号生成器配置
Snowflake:
  #工作中心ID 0-31
  workerId: ${random.int[0,31]}
  #数据中心ID(0~31)
  datacenterId: ${random.int[0,31]}

#增加cloud配置
eureka:
    instance:
        hostname: ${spring.cloud.client.ipAddress}
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        #ip-address位本服务的部署地址
        #ip-address: 172.18.0.7
    client:
        serviceUrl:
            #defaultZone: http://localhost:8761/eureka/
            defaultZone: http://192.168.1.222:8761/eureka/
                    # docker 部署开启
            #defaultZone: http://${EUREKA_HOST:center1.bibitrip.com}:${EUREKA_PORT:8761}/eureka/,http://${EUREKA_HOST:center2.bibitrip.com}:${EUREKA_PORT:8761}/eureka/,http://${EUREKA_HOST:center3.bibitrip.com}:${EUREKA_PORT:8761}/eureka/
            #defaultZone: http://${EUREKA_HOST:172.18.0.7}:${EUREKA_PORT:8761}/eureka/,http://${EUREKA_HOST:172.18.0.6}:${EUREKA_PORT:8761}/eureka/,http://${EUREKA_HOST:172.18.0.5}:${EUREKA_PORT:8761}/eureka/
# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

mq:
    prefix: dev
card:
    post:
        url: http://ms.bibi321.com/api/user/makeDistProfitSplitByPay?
