#redis:
#  database: 12 # 与webrtc-live-cms-service共享使用独立DB（不能与企业服务、支付服务等其他服务使用相同的DB）
#  host: 127.0.0.1
#  port: 6379
#  password:
#
#rabbitmq:
#  nameSpace: DATA-PROCESS
#  host: 127.0.0.1
#  port: 5672
#  virtualHost: /
#  username: guest
#  password: guest

# server
server:
  port: 8000
  servlet:
    register-default-servlet: true
#  ssl:
#    enabled: false
#    key-store: classpath:openvidu-selfsigned.jks
#    key-store-password: openvidu
#    key-store-type: JKS
#    key-alias: openvidu-selfsigned
#server.ssl.key-store=classpath:rtc.wljiam.com.pfx
#server.ssl.key-store-password=1qPYY3rW
#server.ssl.keyStoreType=PKCS12

spring:
  application:
      name: dataManager
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://119.23.35.193:35001/custom?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          username: custom
          password: 9Qhb5OaAS6eJYqAV
          driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
#  redis:
#    database: ${redis.database}
#    host: ${redis.host}
#    port: ${redis.port}
#    password: ${redis.password}
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数(使用负值表示没有限制) 默认为8
#        max-wait: -1ms # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
#        max-idle: 8 # 连接池中的最大空闲连接 默认为8
#        min-idle: 0 # 连接池中的最小空闲连接 默认为 0
  #    jedis:
  #      pool:
  #        max-idle: 20
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
#  rabbitmq:
#    host: ${rabbitmq.host}
#    port: ${rabbitmq.port}
#    virtualHost: ${rabbitmq.virtualHost}
#    username: ${rabbitmq.username}
#    password: ${rabbitmq.password}
#    #    支持发布确认
#    #      publisher-confirms: true
#    #    支持发布返回
#    #      publisher-returns: true
#    listener:
#      simple:
#        #      采用手动应答
#        #acknowledge-mode: manual
#        acknowledge-mode: auto
#        #        当前监听容器数
#        concurrency: 1
#        #        最大数
#        max-concurrency: 1
#        #        是否支持重试
#        retry:
#          enabled: true

  servlet:
    multipart:
      max-file-size:  5MB
      max-request-size: 5MB

  web:
    resources:
      static-locations: classpath:templates/,classpath:static/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.futuremap.custom.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#文件上传目录
prop:
  upload-folder: /usr/local/wwwroot/data/
  download-url: http://test.custom.futuremap.com.cn/upload/
swagger.enable: true
security:
  token:
    header: X-Auth-Token
    secret: ca$hc0w1!
socketio:
  port: 8091
mapper:
  mappers: org.modelmapper.ModelMapper
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring.servlet.multipart.max-file-size: 3MB
spring.servlet.multipart.max-request-size: 5MB

#Twitter_Snowflake 序列号生成器配置
Snowflake:
  #工作中心ID 0-31
  workerId: ${random.int[0,31]}
  #数据中心ID(0~31)
  datacenterId: ${random.int[0,31]}

# swagger
swagger:
  version: 1.0.0
  license: 未来地图
  licenseUrl: https://www.futuremap.com.cn
  termsOfServiceUrl: https://www.futuremap.com.cn
  contact:
    name: pullwind
    url: https://www.futuremap.com.cn
    email: pullwind@futuremap.com.cn

  title: dataManager
  description: 个性化配置服务
  base-package: com.futuremap

  #仅仅在开发模式下才能开启
  enabled: true

rsa:
  key:
    pubKeyPath: E:\\projects\\rsa\\rsa_key.pub
    priKeyPath: E:\\projects\\rsa\\rsa_key
